name: CI
on:
  pull_request:
  push:
      branches:
        - 'dev' # push on dev, if CI green then fast-forward master into dev
      tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, version: '1.0', arch: x64} # oldest supported
          - { os: ubuntu-latest, version: '1.10', arch: x64} # LTS
          - { os: ubuntu-latest, version: '1', arch: x64}
          - { os: ubuntu-latest, version: 'nightly', arch: x64}
          - { os: windows-latest, version: '1', arch: x64}
          - { os: macOS-latest, version: '1', arch: x64}

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - run: |
          git config --global user.name Tester
          git config --global user.email te@st.er

      - uses: julia-actions/julia-runtest@latest
